(INFO) 2024-01-05 14:11:31: === 加载模型:weights/sam_vit_l_0b3195.pth 开始计时……
(INFO) 2024-01-05 14:11:35: === 加载模型:weights/sam_vit_l_0b3195.pth 耗时 4001ms
(INFO) 2024-01-05 14:11:40: === Post全程 开始计时……
(INFO) 2024-01-05 14:11:40: body_dict: {'imgPath': 'imgs/kaola.jpg', 'preMask': 'imgs/result3.png', 'resultPath': 'imgs/result8.png', 'box': {'xmin': 752, 'ymin': 404, 'xmax': 1267, 'ymax': 958}, 'maskColor': {'R': 0, 'G': 255, 'B': 0, 'A': 200}, 'click': [{'x': 1189, 'y': 834, 'is_positive': True}]}
(INFO) 2024-01-05 14:11:40: === Wrapper内部 开始计时……
(INFO) 2024-01-05 14:11:40: === Read img imgs/kaola.jpg 开始计时……
(INFO) 2024-01-05 14:11:40: === Read img imgs/kaola.jpg 耗时 36ms
(INFO) 2024-01-05 14:11:40: === Read img imgs/kaola.jpg --> 颜色转换 耗时 49ms
(INFO) 2024-01-05 14:11:40: === Read img imgs/result3.png 开始计时……
(INFO) 2024-01-05 14:11:40: === Read img imgs/result3.png 耗时 36ms
(INFO) 2024-01-05 14:11:40: === mask_input loaded from: imgs/result3.png.npy
(INFO) 2024-01-05 14:11:40: === Wrapper内部 --> 读图 耗时 87ms
(INFO) 2024-01-05 14:11:40: === Wrapper内部 --> 初始化Predictor 耗时 87ms
(ERROR) 2024-01-05 14:11:40: Failed to predict.
Traceback (most recent call last):
  File "/home/jyf/code/sam/fast_seg/app.py", line 335, in post
    mask_path = self.model.predict(body_dict)
  File "/home/jyf/code/sam/fast_seg/app.py", line 230, in predict
    predictor.set_image(image, cache, image_hash)
TypeError: set_image() takes from 2 to 3 positional arguments but 4 were given
